### ISSUE TITLE
No ESP8266 support?

### ISSUE THREAD

**Issue by himijendrix24** [hideakitai/ArduinoOSC#1]
Using a nodeMCU v2.

If I try to compile the example files, I get the error 
`#error UNSUPPORTED PLATFORM`

After adding
`#define ESP_PLATFORM 1`

it's still not working: 
`Poti_AP_OSC:27: error: 'osc' does not name a type
 osc.begin(udp, recv_port);`

**Comment by hideakitai** [comment]
Sorry, I will remove error about `ESP8266`.
But maybe you can build it by changing:
- add `#define ESP_PLATFORM`
- rewrite WIFi related stuff based on your platform manner, or remove them

I could build it in ESP8266 Generic Module and NodeMCU v1.0
(I couldn't find v2 in board manager)

**Comment by hideakitai** [comment]
@himijendrix24 I have tested on NodeMCU v1, and worked fine. Please try version 0.1.2. Thanks.
