### ISSUE TITLE
errors compiling the OscEtherUno sketch 

### ISSUE THREAD

**Issue by sevdh** [hideakitai/ArduinoOSC#20]
I'm using the latest Arduino IDE (1.8.15) with the latest ArduinoOSC library.

I'm getting the following errors when I'm trying to compile the OscEtherUno sketch (see below):

What am I doing wrong?

Best regards! Edwin

In file included from /Users/USER/Documents/Arduino/libraries/ArduinoOSC/ArduinoOSC.h:59:0,
                 from /Users/USER/Documents/Arduino/libraries/ArduinoOSC/examples/arduino/OscEtherUno/OscEtherUno.ino:17:
/Users/USER/Documents/Arduino/libraries/ArduinoOSC/ArduinoOSC/OscUdpMap.h: In instantiation of 'arduino::osc::UdpRef<S> arduino::osc::UdpMapManager<S>::getUdp(uint16_t) [with S = EthernetUDP; arduino::osc::UdpRef<S> = arx::stdx::shared_ptr<EthernetUDP>; uint16_t = unsigned int]':
/Users/USER/Documents/Arduino/libraries/ArduinoOSC/ArduinoOSC/OSCServer.h:208:22:   required from 'bool arduino::osc::server::Server<S>::parse() [with S = EthernetUDP]'
/Users/USER/Documents/Arduino/libraries/ArduinoOSC/examples/arduino/OscEtherUno/OscEtherUno.ino:78:22:   required from here
/Users/USER/Documents/Arduino/libraries/ArduinoOSC/ArduinoOSC/OscUdpMap.h:53:21: error: call of overloaded 'erase(const uint16_t&)' is ambiguous
                     udp_map.erase(PORT_DISCARD);
                     ^~~~~~~
In file included from /Users/USER/Documents/Arduino/libraries/ArduinoOSC/ArduinoOSC.h:6:0,
                 from /Users/USER/Documents/Arduino/libraries/ArduinoOSC/examples/arduino/OscEtherUno/OscEtherUno.ino:17:
/Users/USER/Documents/Arduino/libraries/ArduinoOSC/ArduinoOSC/util/ArxContainer/ArxContainer.h:679:14: note: candidate: arx::map<Key, T, N>::iterator arx::map<Key, T, N>::erase(const Key&) [with Key = unsigned int; T = arx::stdx::shared_ptr<EthernetUDP>; unsigned int N = 2; arx::map<Key, T, N>::iterator = arx::RingBuffer<arx::pair<unsigned int, arx::stdx::shared_ptr<EthernetUDP> >, 2>::Iterator]
     iterator erase(const Key& key) {
              ^~~~~
/Users/USER/Documents/Arduino/libraries/ArduinoOSC/ArduinoOSC/util/ArxContainer/ArxContainer.h:684:14: note: candidate: arx::map<Key, T, N>::iterator arx::map<Key, T, N>::erase(size_t) [with Key = unsigned int; T = arx::stdx::shared_ptr<EthernetUDP>; unsigned int N = 2; arx::map<Key, T, N>::iterator = arx::RingBuffer<arx::pair<unsigned int, arx::stdx::shared_ptr<EthernetUDP> >, 2>::Iterator; size_t = unsigned int]
     iterator erase(const size_t index) {
              ^~~~~
exit status 1
Error compiling for board Arduino Uno.

**Comment by hideakitai** [comment]
@sevdh Thank you for reporting, fixed in v0.3.22!
