### ISSUE TITLE
Compilation error when including ArduinoOSC.h in a C++ header

### ISSUE THREAD

**Issue by VonHirsch** [hideakitai/ArduinoOSC#22]
This isn't my post but it summarizes the issue well:

https://www.gitmemory.com/issue/hideakitai/ArduinoOSC/5/529086213

I tried using a forward declaration in my header ("class OscMessage") but then realized it's not allowed with "OscMessage &m" using the "address of" operator.

Thanks for the lib!

**Comment by hideakitai** [comment]
Hi, thank you for reporting. Could you give me a minimum code that can reproduce the compile error?

**Comment by VonHirsch** [comment]
Sure, https://github.com/hideakitai/ArduinoOSC/pull/23

**Comment by VonHirsch** [comment]
let me know what you find out, hopefully it's something i'm doing wrong :)

**Comment by hideakitai** [comment]
Thank you! Probably fixed in v0.3.24. Could you try it again?

**Comment by VonHirsch** [comment]
confirmed fixed, thanks!
