### ISSUE TITLE
ESP32 AP mode

### ISSUE THREAD

**Issue by ChristopheLebreton** [hideakitai/ArduinoOSC#27]
Hi,

Static mode work perfectly but I don't have any success to use ArduinoOSC with AP mode wifi.
there's a way to use ArduinoSOC with AP mode with a ESP32 ?

Bets & thx for your great library ;)

Chris

**Comment by ChristopheLebreton** [comment]
just to know ESP32 & wifi AP mode worked with ArduinoOSC 0.3.8 but not with current version 0.3.26
if you have a idea of the reason it's welcome, else I'll take time asap to search
best ;)
Chris

**Comment by hideakitai** [comment]
@ChristopheLebreton Hi, could you give me your ESP32's firmware version and minimum reproducible code? Thanks for reporting!

**Comment by ChristopheLebreton** [comment]
@hideakitai Hi, just to know AP mode doesn't work until 0.3.13 ( 0.3.12 works ;)
ESP32 Chip model = ESP32-D0WDQ6 Rev 1

please find below a basic code to test it to switch on/off a LED through OSC :
it works in AP mode with ArduinoOSC 0.3.12, not after revision.
//========================================================
#include <ArduinoOSC.h>
//#include <ArduinoOSCWiFi.h> // used with 3.17 but AP mode doesn't works until 3.13
#define ARDUINOOSC_DEBUGLOG_ENABLE

#include <WiFi.h>  // Utilisation de la librairie WiFi.h

//========= WIFI network =============

const char* ssid = "ESP32AP"; // name of Wifi
const char* pwd = "123456789"; // password


//------- for ArduinoOSC.h library -------
const char* host = "192.168.1.2";
const int recv_port = 54321;
const int bind_port = 54345;
const int send_port = 55555;
const int publish_port = 54445;

const int output26 = 26;
int setLED = 1;

void setup()
{    
    //========= Serias INIT =============
    Serial.begin(115200); 
    delay(2000);

    //========= WIFI INIT =============
    //WiFi.disconnect();
    //delay(1000);
    WiFi.mode(WIFI_MODE_AP);
    WiFi.begin(ssid, pwd);

    Serial.print("ESP32 Adresse IP: ");
    Serial.println(WiFi.softAPIP());
    
    pinMode(output26, OUTPUT);
    digitalWrite(output26, LOW);

    //========= OSC =============
    //---- Subscribe -> Receive OSC messages ----
    // define through OSC message : threshold, sensitivity, note
    OscWiFi.subscribe(bind_port, "/setLED", setLED);
    
}

void loop()
{ 
  OscWiFi.parse(); 

  digitalWrite(output26, setLED);
  delay(100);
  

}

**Comment by hideakitai** [comment]
@ChristopheLebreton Sorry for the late reply. I've fixed this in v0.3.28. Please try it and if there is a problem, feel free to reopen.

**Comment by ChristopheLebreton** [comment]
Hi,

thx it’s works now ;)

Best regards

Chris
