### ISSUE TITLE
Example with OSC over Serial using MsgPacketizer

### ISSUE THREAD

**Issue by leutholl** [hideakitai/ArduinoOSC#31]
Hi
I need to send osc messages from a Teensy to a ESP µP (with Wifi) over Serial. Since you dropped support for OscSerial and I also do not see SLIP support and seeing that you recommend MsgPacketizer can you please create a very simple example sketch on how a OSC message that would normally go out over Ethernet will be sent to Serial (encoded to support all data types) and maybe the counterpart to read from Serial, parse it as a OSCMessage and send it over Wifi. How can your Manager class be wrapped to Serial/SLIP/MsgPacketizer so that we can use the same high-level API to send and receive without going into byte-romantics?
Alternatively you can show the approach here in this Issue thread. This would make the library even better than it already is. Many thanks and congrats to this wonderful piece of work!

**Comment by hideakitai** [comment]
Sorry, I don't plan to re-support OSC over Serial (SLIP). Please use the "OSC" library for serial support.

https://github.com/CNMAT/OSC
