### ISSUE TITLE
Teensy 4.1 Native Ethernet support

### ISSUE THREAD

**Issue by zarpli** [hideakitai/ArduinoOSC#32]
any hope of supporting Teensy 4.1 Native Ethernet?

**Comment by hideakitai** [comment]
There is experimental branch for native ethernet of Teensy 4.1 https://github.com/hideakitai/ArduinoOSC/tree/t41_native_ethernet

**Comment by zarpli** [comment]
> There is experimental branch for native ethernet of Teensy 4.1 https://github.com/hideakitai/ArduinoOSC/tree/t41_native_ethernet

works as expected

thanks!
