### ISSUE TITLE
now the dependencies must be installed separately?

### ISSUE THREAD

**Issue by zarpli** [hideakitai/ArduinoOSC#45]
hi,

DebugLog, ArxContainer, ArxSmartPtr, ArxTypeTraits, must be installed separately?

**Comment by zarpli** [comment]
It was only necessary to restart the arduino IDE, after the arduioOSC update

**Comment by zarpli** [comment]
Yes, it is necessary to install the dependencies manually :(.

**Comment by hideakitai** [comment]
Please re-install ArduinoOSC. Dependent libraries will be installed automatically.

**Comment by hideakitai** [comment]
Added note to README about the removal of dependent libraries

**Comment by zarpli** [comment]
thanks!
