### ISSUE TITLE
Example for Uno WiFi

### ISSUE THREAD

**Issue by marcvillanuevamir** [hideakitai/ArduinoOSC#59]
Hi! Thank you so much for this amazing library! I am trying to use it with the UNO R4 WiFi, and I wonder: should I use the Uno version of the code as you point out? In that case, there is only an Ethernet-based example. Could you tell me how should I use this with WiFi too? Or do you think that with the larger memory of the R4 I would be good using publishers? Thank you so much!

**Comment by hideakitai** [comment]
@marcvillanuevamir For Uno R4, please use [OscWifi.ino](https://github.com/hideakitai/ArduinoOSC/blob/main/examples/arduino/OscWiFi/OscWiFi.ino).

**Comment by marcvillanuevamir** [comment]
Thank you!!
