### ISSUE TITLE
#include path typo

### ISSUE THREAD

**Issue by Maigre** [hideakitai/ArduinoOSC#7]
Hi,
in ArduinoOSC.h the 2 includes at the beginning have typo:

#include "ArduinoOSC/OscServer.h"
#include "ArduinoOSC/OscClient.h"

should be 

#include "ArduinoOSC/OSCServer.h"
#include "ArduinoOSC/OSCClient.h"

Best,

**Comment by hideakitai** [comment]
Thank you very very much!! I fixed it in version 0.2.2
